### ISSUE TITLE
Relies on making sheets public

### ISSUE THREAD

**Issue by theronic** [ReilySiegel/clojure-sheets#2]
Fair warning to others: you have to make sheets public to use the Publish feature.

**Comment by ReilySiegel** [comment]
This is correct. However, I don't feel that that is necessarily a reason in itself to not use this library. Personally, I use this code to store user-facing data on a website in a way that non-technical people can edit, without building a dedicated UI/server. Specifically, my Sheet contains bio information for the members of an organization. I initially didn't feel I needed to draw explicit attention to this drawback, as making a sheet public and publishing it is part of the setup process. However, since you feel it merits a stronger warning, I will add a section to the README explaining that this should only be used for public-facing information.
